# Generated by Django 3.1.2 on 2020-10-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201030_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpassword',
            name='token',
        ),
    ]
